# change the followings to match your Github username and repo name
baseurl: "https://reubenwasser.github.io" # the name of your github repo
url: "https://reubenwasser.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Reuben Wasser"
description: Data informed journalism with a soul

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Reuben Wasser
author-bio: Placeholder # change to false to hide
author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Bitcoin
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/
linkedin: https://linkedin.com/
medium: false
google-scholar: false
email: mailto:reuben.wasser@gmail.com

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
